on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
      id: checkout
      with:
        submodules: true
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - run: mkdir -p ${{ runner.temp }}/protoc
    - run: |
        curl -Lo protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v31.0/protoc-31.0-linux-x86_64.zip
        unzip protoc.zip
        echo "$PWD/bin" >> "$GITHUB_PATH"
      working-directory: ${{ runner.temp }}/protoc
    - run: go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36
    - run: make docs-output/index.md
    - uses: actions/jekyll-build-pages@v1
      with:
        source: docs-output
    - uses: actions/upload-pages-artifact@v3
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/deploy-pages@v4
      id: deployment
